### ISSUE TITLE
报错信息怎么查看呢

### ISSUE THREAD

**Issue by molun** [yfdoor/OpenWrt#10]
![image](https://user-images.githubusercontent.com/23138506/81374489-f18a0200-9131-11ea-878d-b23ea30f2a0b.png)

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/81374717-78d77580-9132-11ea-889a-322f9ff170eb.png)
竟然生成的是x86
![image](https://user-images.githubusercontent.com/23138506/81374744-8c82dc00-9132-11ea-99b1-5445051e6cfd.png)

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/81374906-eb485580-9132-11ea-91d0-c840ea8d34c4.png)
![image](https://user-images.githubusercontent.com/23138506/81374935-f602ea80-9132-11ea-9d5f-2e12e6029c0a.png)

**Comment by yfdoor** [comment]
![2020-05-10](https://user-images.githubusercontent.com/32769281/81494889-c55fb400-92de-11ea-8c15-63e15945f6e7.png)

View Log
