### ISSUE TITLE
请教下，能否出一个make menuconfig的教程

### ISSUE THREAD

**Issue by molun** [yfdoor/OpenWrt#3]
以某一个硬路由为例，比如极路由hc5962，具有USB2.0、USB3.0接口，添加IPV6等

万分感谢！

**Comment by yfdoor** [comment]
这个。。百度一下很多教程的吧，前提是你了解自己路由的型号，选好target 就行，你要是有物理机编译环境的话，执行 make menuconfig 一看便知。
