### ISSUE TITLE
云make menuconfig问题

### ISSUE THREAD

**Issue by molun** [yfdoor/OpenWrt#4]
SSH_ACTION: 由false设置为true，日志中打不开，出现不了ssh连接地址，是偶然卡顿还是需要在其他地方进行调整

**Comment by yfdoor** [comment]
> SSH_ACTION: 由false设置为true，日志中打不开，出现不了ssh连接地址，是偶然卡顿还是需要在其他地方进行调整

是的，设置为true即可，我之前有时候也出现过这种情况，不知道是debugger-action的问题还是咱们国内访问慢的缘故。
