### ISSUE TITLE
SSH連接進入顯示不正常

### ISSUE THREAD

**Issue by molun** [yfdoor/OpenWrt#5]
字符都是散開的，和P3TERX的不太一樣
![Snipaste_2020-03-26_11-36-22](https://user-images.githubusercontent.com/23138506/77608193-7ee50e80-6f57-11ea-9ce7-c14b6415fbc1.png)

**Comment by yfdoor** [comment]
> 字符都是散開的，和P3TERX的不太一樣
> ![Snipaste_2020-03-26_11-36-22](https://user-images.githubusercontent.com/23138506/77608193-7ee50e80-6f57-11ea-9ce7-c14b6415fbc1.png)
你这个看上去是编码的问题，ssh功能需要调用 debug-action,这个功能我是从p3t那边fork来的，之前试过没什么问题的。说实话这个功能有些鸡肋，主要是国内连接速度太慢。。
