### ISSUE TITLE
fork项目尝试编译失败，请教设置问题

### ISSUE THREAD

**Issue by molun** [yfdoor/OpenWrt#6]
fork后需要进行什么参数的修改设置吗

**Comment by yfdoor** [comment]
要看你的报错代码，需要设置自己的secret token

**Comment by molun** [comment]
是不是在Secrets中填写Personal access tokens

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/77720481-051a5700-7023-11ea-85a5-71ff1eb88231.png)
这个地方要调整吗

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/77720572-41e64e00-7023-11ea-8853-06a031af78c3.png)
这样对吗，内容填写Personal access tokens

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/77723084-6691f400-702a-11ea-8d3a-fbf226255654.png)
退出代码128 你的配置没有动

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/77723133-86291c80-702a-11ea-8ee5-6ccd5ea14891.png)


> ![image](https://user-images.githubusercontent.com/23138506/77723084-6691f400-702a-11ea-8d3a-fbf226255654.png)
> 退出代码128 你的配置没有动

![image](https://user-images.githubusercontent.com/23138506/77723138-8a553a00-702a-11ea-8b69-3cc4570ba45b.png)

**Comment by yfdoor** [comment]
> 是不是在Secrets中填写Personal access tokens

个人的Settings Developer settings 中先设置 Personal access tokens， 给 repo 的相关权限，然后在 相应 repo 的 setting 中 Secrets 添加 该 token

**Comment by yfdoor** [comment]
> ![image](https://user-images.githubusercontent.com/23138506/77720481-051a5700-7023-11ea-85a5-71ff1eb88231.png)
> 这个地方要调整吗

下面的路径一定要改成你自己的项目路径啊，上面的无所谓

**Comment by yfdoor** [comment]
> ![image](https://user-images.githubusercontent.com/23138506/77723133-86291c80-702a-11ea-8ee5-6ccd5ea14891.png)
> 
> > ![image](https://user-images.githubusercontent.com/23138506/77723084-6691f400-702a-11ea-8d3a-fbf226255654.png)
> > 退出代码128 你的配置没有动
> 
> ![image](https://user-images.githubusercontent.com/23138506/77723138-8a553a00-702a-11ea-8b69-3cc4570ba45b.png)

我去你的项目下看了一下，现在的报错是由于 token secret 的事情，设置对了再看看

**Comment by molun** [comment]
> 
> 我去你的项目下看了一下，现在的报错是由于 token secret 的事情，设置对了再看看

![image](https://user-images.githubusercontent.com/23138506/77813307-913f8380-70e2-11ea-8299-93375c02e156.png)
这里对吧

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/77813348-eda2a300-70e2-11ea-999f-41b7e78c566f.png)

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/77813460-c9939180-70e3-11ea-98ad-14371a4dbdb6.png)
还是要替换掉这里

**Comment by yfdoor** [comment]
> ![image](https://user-images.githubusercontent.com/23138506/77813460-c9939180-70e3-11ea-98ad-14371a4dbdb6.png)
> 还是要替换掉这里

是的， REPO_TOKEN 换成你自己起的 secret 名字

**Comment by molun** [comment]
![image](https://user-images.githubusercontent.com/23138506/77850988-d1008b00-7208-11ea-8240-4eb9204f66ea.png)

**Comment by yfdoor** [comment]
我看你的项目已经编译成功了，我先close了，有问题咱们再讨论
