### ISSUE TITLE
不知道为啥使用lede源就编译失败

### ISSUE THREAD

**Issue by molun** [yfdoor/OpenWrt#7]
帮忙看看hc5962这个

**Comment by yfdoor** [comment]
这个不应该啊，直接编译单一源码，什么都不修改，应该是最不会出问题的才对。可能是他那边最近改动的有 bug 吧，L 大那边的源码每天很多修改，偶尔可能会有个别版本编译不过去吧，你可以去他那边的issue 区看看，有没有人也有一样的问题，或者明天再试试。
