### ISSUE TITLE
增加创建分支

### ISSUE THREAD

**Issue by ClayMoreBoy** [yfdoor/OpenWrt#9]
Process completed with exit code 1.
https://github.com/ClayMoreBoy/OpenWrt/runs/562108166?check_suite_focus=true

**Comment by yfdoor** [comment]
> Process completed with exit code 1.
> https://github.com/ClayMoreBoy/OpenWrt/runs/562108166?check_suite_focus=true

你这个改的有问题：

>176   cp openwrt/.config .

**Comment by ClayMoreBoy** [comment]
后来改了说文件过大 guthub 只支持50MB以内的zip

**Comment by yfdoor** [comment]
> 后来改了说文件过大 guthub 只支持50MB以内的zip

50M 没问题的，只是警告，但是还是会上传的，100M 以上才会被拒绝，但是我代码设置了大于100M会分卷压缩的。
